Arduino TempProbe changes WIP
Open-Acidification/TankControllerLib pull request #11
Opened 2020-11-02 17:03 UTC by cherbel

This does not work due to the issue submitted here:
https://github.com/Arduino-CI/arduino_ci/issues/192

2020-11-04 05:09 UTC, jgfoster commented
We are also waiting on https://github.com/Arduino-CI/arduino_ci/issues/193.

2020-11-13 21:27 UTC, ianfixes commented
I think the problem is elsewhere, see https://github.com/cherbel/TankControllerLib/pull/1

2020-11-14 03:42 UTC, ianfixes commented
It looks like you might be [checking out the wrong branch](https://github.com/Open-Acidification/TankControllerLib/blob/master/scripts/install_libraries.sh#L19) in your install script:

```bash
# get custom version of Adafruit_MAX31865
git clone https://github.com/Arduino-CI/Adafruit_MAX31865.git
mv Adafruit_MAX31865 $(bundle exec arduino_library_location.rb)
```

The [error you're getting about `Adafruit_MAX31865_CI.h: No such file or directory `](https://github.com/Open-Acidification/TankControllerLib/runs/1398445342#step:6:64) makes sense because the `Adafruit_MAX31865_CI.h` file is located in [the `arduino_ci` branch of `Arduino-CI/Adafruit_MAX31865`](https://github.com/Arduino-CI/Adafruit_MAX31865/tree/arduino_ci/src), and in the snippet above you're just cloning the master branch.

2020-11-15 04:49 UTC, jgfoster commented
See https://github.com/Arduino-CI/arduino_ci/pull/212 for an example of what we are trying to do.

2020-11-20 19:40 UTC, ianfixes commented
I just merged `arduino_ci` code that should fix this issue

2020-11-24 23:14 UTC, cherbel commented
@jgfoster I think this is ready to be merged.

2020-11-25 02:31 UTC, prestoncarman requested changes

2020-11-25 02:31 UTC, prestoncarman commented on src/Devices/TempProbe_TC.h
> +// Adafruit MAX31865
Please convert this to a multi-line comment to allow it to show in documentation.

2020-11-25 02:33 UTC, prestoncarman commented
If this is ready, please update the PR title and description.

2020-11-27 19:46 UTC, prestoncarman approved these changes
LGTM

2020-11-27 20:09 UTC, merged

2021-02-20 00:34 UTC, prestoncarman commented
@all-contributors please add @cherbel for code