Ethernet
Open-Acidification/TankControllerLib pull request #41
Opened 2021-01-19 18:10 UTC by Kavikick

2021-02-02 00:39 UTC, prestoncarman commented on src/Devices/Ethernet_TC.h
> +Based off Arduino's Ethernet library
Use the following comment style. For at the start of files, classes and functions.

```
/**
 *
 */
```

2021-02-09 17:38 UTC, jgfoster requested changes
While we investigate the other test failures, could you fix the formatting issues?

2021-02-09 23:47 UTC, jgfoster approved these changes
LGTM

2021-02-10 22:19 UTC, prestoncarman approved these changes
LGTM

2021-02-10 22:19 UTC, merged

2021-02-19 23:57 UTC, prestoncarman commented
@all-contributors please add @Kavikick for code