DateTime class wrapper
Open-Acidification/TankControllerLib pull request #54
Opened 2021-02-16 22:04 UTC by eucalvo

Added the wrapper and tests for DateTime class.

2021-02-22 22:13 UTC, jgfoster requested changes

2021-02-22 22:13 UTC, jgfoster commented on test/DateTime.cpp
> +  DateTime_TC dob(2001, 2, 20, 3, 50, 10);
To minimize revealing info, let's just use `jan` as "now" and adjust following lines of asserts.

2021-02-22 22:13 UTC, jgfoster commented on test/DateTime.cpp
>  //  void printToSerial();   // DigitalClockDisplay.ino
This code came from ... in the older version of TankController.ino.

2021-02-22 22:13 UTC, jgfoster commented on test/DateTime.cpp
singleton test that the function returns the identical object each time.

2021-02-23 22:34 UTC, prestoncarman approved these changes
LGTM

2021-03-02 00:48 UTC, jgfoster approved these changes
LGTM

2021-03-02 00:48 UTC, merged