Number collector state
Open-Acidification/TankControllerLib pull request #56
Opened 2021-02-19 04:49 UTC by Kavikick

2021-02-19 04:51 UTC, Kavikick commented
Feedback on what characters to use for the extended features would be appreciated. I don't know which ones would be best.

2021-02-19 05:01 UTC, jgfoster requested changes
This is a very good start and demonstrates nicely the simplicity and elegance of the approach. Take a look at my comments and let me know if you would like more clarification.

2021-02-19 05:01 UTC, jgfoster commented on src/UIState/NumberCollectorState.cpp
> +  } else if (key == '-') {  // backspace
Our keypad has 0-9, *, #, and A-D. So the keys used will need to be adjusted.

2021-02-19 05:01 UTC, jgfoster commented on src/UIState/NumberCollectorState.h
> + * Abstract superclass for the NumberCollector UI states
If this is a truly abstract class, then we need to have a concrete subclass, even for testing. You indicate an abstract superclass by having a function prototype with `= 0` as part of its definition.

2021-02-19 05:01 UTC, jgfoster commented on src/UIState/NumberCollectorState.h
> +  NumCollectorState(int digits) {
Will each subclass have a known number of digits? If so, then no need to make it a configurable parameter. Instead have a `virtual` function that returns the desired value.

Also, it appears that you are collecting integers; I don't see anything here for fixed-point numbers (which is what many of our states will need.

2021-02-19 05:01 UTC, jgfoster commented on .github/actions/spelling/expect.txt
> +namespace
Is this the first file with `namespace`? Do the others just preface all the names with `std::`? See https://www.geeksforgeeks.org/using-namespace-std-considered-bad-practice/.

2021-02-19 05:09 UTC, jgfoster commented on src/UIState/NumberCollectorState.cpp
> +  } else if (key == '-') {  // backspace
Proposal:

- `*`: decimal point (alternative is to have it fixed and have digits jump over it)
- `A`: enter (all done!)
- `B`: backspace
- `C`: clear
- `D`: cancel (don't finish!)

2021-03-02 03:53 UTC, jgfoster requested changes

2021-03-02 03:53 UTC, jgfoster commented on .github/actions/spelling/expect.txt
> +namespace
Thought on `namespace`?

2021-03-02 03:53 UTC, jgfoster commented on src/UIState/NumberCollectorState.cpp
> +void NumCollectorState::handleDigit(double digit) {
Why is digit a `double`?

2021-03-02 03:53 UTC, jgfoster commented on src/UIState/NumberCollectorState.cpp
> +    numDigits--;
How about backspacing over the decimal point?

2021-03-02 03:53 UTC, jgfoster commented on src/UIState/NumberCollectorState.h
> +    LiquidCrystal_TC::instance()->writeLine(" ", 1);
Does this replace the entire line or only the first character? We might need to write sixteen spaces.

2021-03-02 03:53 UTC, jgfoster commented on src/UIState/NumberCollectorState.h
> +  bool noDecimal = true;
You might think about phrasing booleans in a positive manner. So `hasDecimal` is `true` or `false` instead of `no` being `true`.

2021-03-02 03:53 UTC, jgfoster commented on test/NumberCollectorState.cpp
> +#include "NumberCollectorState.h"
Nice set of tests!

2021-03-02 16:51 UTC, jgfoster approved these changes
LGTM

2021-03-04 04:39 UTC, prestoncarman approved these changes
LGTM

2021-03-04 04:48 UTC, merged